# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resources', models.TextField()),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('ON', 'Ongoing'), ('PO', 'Postponed'), ('AB', 'Aborted'), ('CO', 'Completed')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quarter', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('ON', 'Ongoing'), ('PO', 'Postponed'), ('AB', 'Aborted'), ('CO', 'Completed')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('ON', 'Ongoing'), ('PO', 'Postponed'), ('AB', 'Aborted'), ('CO', 'Completed')], max_length=2)),
                ('priority_area', models.CharField(choices=[('PR', 'Program'), ('IM', 'Impact'), ('EX', 'External recognition'), ('FU', 'Funding'), ('TA', 'Talent')], max_length=2)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('ON', 'Ongoing'), ('PO', 'Postponed'), ('AB', 'Aborted'), ('CO', 'Completed')], max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='assignee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Volunteer'),
        ),
        migrations.AddField(
            model_name='project',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Strategy'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='partnership_manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_manager', to='web.PartnershipManager'),
        ),
    ]
