# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmaUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('V', 'Volunteers'), ('P', 'Project manager')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_name', models.TextField()),
                ('badge_type', models.CharField(choices=[('V', 'Volunteer'), ('P', 'Partnership manager')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resources', models.TextField()),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('ON', 'Ongoing'), ('PO', 'Postponed'), ('AB', 'Aborted'), ('CO', 'Completed')], max_length=2)),
                ('hello', models.TextField()),
                ('partnership_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quarter', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('ON', 'Ongoing'), ('PO', 'Postponed'), ('AB', 'Aborted'), ('CO', 'Completed')], max_length=2)),
                ('assignee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('ON', 'Ongoing'), ('PO', 'Postponed'), ('AB', 'Aborted'), ('CO', 'Completed')], max_length=2)),
                ('priority_area', models.CharField(choices=[('PR', 'Program'), ('IM', 'Impact'), ('EX', 'External recognition'), ('FU', 'Funding'), ('TA', 'Talent')], max_length=2)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('ON', 'Ongoing'), ('PO', 'Postponed'), ('AB', 'Aborted'), ('CO', 'Completed')], max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Strategy'),
        ),
    ]
