# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='hello',
        ),
    ]
