# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_ngo_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmauserinfo',
            name='last_checked_in_time',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 19, 23, 9, 638888, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atmauserinfo',
            name='streak',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
