# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160724_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='description',
            new_name='priority_area',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='ngo',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='priority_name',
        ),
    ]
