# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160724_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_name',
        ),
    ]
