# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160724_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='strategy',
        ),
    ]
