# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_project_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='strategy',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
