# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20160724_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Strategy'),
        ),
    ]
