# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20160724_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
